api_listen: 127.0.0.1:9000  # will allow local connections only
api_expvar_path: null  # not exposed
apigeesync_proxy_server_base: http://localhost:9001/edgex
apigeesync_snapshot_server_base: http://localhost:9001/edgex
apigeesync_change_server_base: http://localhost:9001/edgex
apidanalytics_uap_server_base: http://local.com:9001/edgex
apigeesync_consumer_key: MDygyE8OD8rlemI7S1XhlUCA7jrarjxl
apigeesync_consumer_secret: oAuKUqRVvFVq0tzS
apigeesync_cluster_id: fc0e5137-d3fa-4017-8bfa-86b1103bc85d
log_level: debug    # valid values: Debug, Info, Warning, Error, Panic, Fatal
