config:
  target: http://34.197.66.95:9000
  plugins:
    statsd:
      host: 34.200.46.239
      port: 8125
      prefix: 'artillery'
  http:
    timeout: 10
  phases:
    - duration: 1200
      arrivalRate: 1
  processor: "./my-functions.js"
  defaults:
    headers:
      x-my-service-auth: '987401838271002188298567'

scenarios:
  -
    name: "Deployments ping"
    flow:
      -
        get:
          url: "/deployments"
          afterResponse: "captureDeployments"
      -
        think: 1
      -
        put:
          url: "/deployments"
          beforeRequest: "fakeStatuses"
